### ISSUE TITLE
Chainsplit features

### ISSUE THREAD

**Issue by jonathanbier** [jonathanbier/forkmonitor#35]
- Implement inflation and deflation detection, by comparing the sum UTXO function to an expected value according to a formula and checking the calculation each block. The formula should do 2 things: 1. expected max coin supply based on block height, and 2. expected change in coin supply from the previous block. Do this on both Bitcoin Core 0.17.1 and an independent implementation, such that there is a double check. After this is implemented, think of a way of displaying this (e.g. coin count) on the site.
- If the nodes are not at the same hash, make the website display differently if it’s a conflicting chain compared to just being behind. If the node is behind, indent the section and put it below the chain ahead of it, to show its only behind
- Finish all the invalid chain checks. Two systems: 1. the getchaintips method (done), and 2. Feeding blocks

**Comment by Sjors** [comment]
This has been split into seperate issues: #84 and #82. Feeding blocks from one node to the other has been implemented somewhat, as well as trying to fetch missing blocks from many different peers.
